ecom_dev:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', '5432') | int }}"
      dbname: "{{ env_var('DBT_DB', 'ecom_dw') }}"
      user: "{{ env_var('DBT_USER', 'user') }}"
      password: "{{ env_var('DBT_PASSWORD', 'password') }}"
      schema: ecom_staging
      threads: 4
      keepalives_idle: 0
  target: dev
